### ISSUE TITLE
_updateMessageStatus doesn’t work on GS 3.6.3.1

### ISSUE THREAD

**Issue by qdii** [screenfreeze/messagingmenu#13]
gnome-shell logs this error:

"'
    JS ERROR: !!!   TypeError: Main.messageTray.getSources is not a function
    JS ERROR: !!!     message = '"Main.messageTray.getSources is not a function"'
    JS ERROR: !!!     fileName = '"/home/qdii/.local/share/gnome-shell/extensions/messagingmenu@screenfreeze.net/extension.js"'
    JS ERROR: !!!     lineNumber = '302'
    JS ERROR: !!!     stack = '"_updateMessageStatus()@/home/qdii/.local/share/gnome-shell/extensions/messagingmenu@screenfreeze.net/extension.js:302
customUpdateCount([object Object])@/home/qdii/.local/share/gnome-shell/extensions/messagingmenu@screenfreeze.net/extension.js:380
_emit("count-updated")@/usr/share/gjs-1.0/signals.js:124
()@/usr/share/gnome-shell/js/ui/messageTray.js:1076
wrapper()@/usr/share/gjs-1.0/lang.js:204
([object Object])@/usr/share/gnome-shell/js/ui/messageTray.js:1158
wrapper([object Object])@/usr/share/gjs-1.0/lang.js:204
([object Object])@/usr/share/gnome-shell/js/ui/messageTray.js:1163
wrapper([object Object])@/usr/share/gjs-1.0/lang.js:204
_parent([object Object])@/usr/share/gjs-1.0/lang.js:166
()@/usr/share/gnome-shell/js/ui/components/telepathyClient.js:702
wrapper()@/usr/share/gjs-1.0/lang.js:204
()@/usr/share/gnome-shell/js/ui/components/telepathyClient.js:687
wrapper()@/usr/share/gjs-1.0/lang.js:204
"'
